### ISSUE TITLE
не запускается контейнер

### ISSUE THREAD

**Issue by combx** [AlexSuperStar/Bitrix24DocxToPdf#1]
есть проблема с запуском FileTransformer  

[+] Running 3/3
 ✔ Network converter_default     Created                                                                                                                0.1s
 ✔ Container FileTransformer     Created                                                                                                                0.3s
 ✔ Container converter-rabbit-1  Created                                                                                                                0.3s
Attaching to FileTransformer, rabbit-1
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer exited with code 0
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer exited with code 255
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21
FileTransformer  | PHP Fatal error:  Uncaught Error: Call to undefined method App::run() in /app/app.php:21
FileTransformer  | Stack trace:
FileTransformer  | #0 {main}
FileTransformer  |   thrown in /app/app.php on line 21

rabbit-1  стартует и ошибок не наблюдается

Как побороть ошибку?

**Comment by AlexSuperStar** [comment]
Код выложен не полностью, поэтому и не работает.

**Comment by combx** [comment]
> Код выложен не полностью, поэтому и не работает.

что надо, чтобы увидеть весь код?
